---
- name: Provision "{{ ec2_count }}" instance(s) with name "{{ ec2_tag_Name }}"
  ec2:
    key_name: "{{ ec2_keypair }}"
    group: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    vpc_subnet_id: "{{ ec2_subnet_id }}"
    zone: "{{ ec2_zone }}"
    region: "{{ ec2_region }}"
    instance_tags: '{"Type":"{{ec2_instance_type}}", "Name":"{{ec2_tag_Name}}"}'
    assign_public_ip: "{{ assign_public_ip }}" 
    wait: true
    exact_count: "{{ ec2_count }}"
    count_tag:
      Name: "{{ ec2_tag_Name }}"
  register: ec2

- name: Wait for the instance(s) to boot by checking the ssh port
  wait_for: 
    host: "{{item.public_ip}}"
    port: 22 
    delay: 15 
    timeout: 300 
    state: started
  with_items: "{{ ec2.instances }}"

- name: Refresh hosts inventory list
  meta: refresh_inventory
