version: '2'
services:
  master:
    build: 
      context: ./master
      dockerfile: Dockerfile
    environment:
        - PG_USER=${POSTGRES_USER}
        - PG_PW=${POSTGRES_PASSWORD}
        - PG_DB=${POSTGRES_DB}
        - REPL_PW=${REPL_PASSWORD}
    volumes:
      - master-data:/var/lib/postgresql/10/main/
  slave:
    build: 
      context: ./slave
      dockerfile: Dockerfile
    environment:
      - REPL_PW=${REPL_PASSWORD}
      - PG_USER=${POSTGRES_USER}
      - PG_DB=${POSTGRES_DB}
    depends_on:
      - master
    volumes:
      - slave-data:/var/lib/postgresql/10/main/
  web:
    build: web/
    depends_on:
      - master
    environment:
      - PG_USER=${POSTGRES_USER}
      - PG_PW=${POSTGRES_PASSWORD}
      - PG_DB=${POSTGRES_DB}
    volumes:
      - app-data:/app/
    ports:
      - "5000:5000"
volumes:
  master-data:
  slave-data:
  app-data:
